services:
  ext_proc_demo_envoy:
    image: istio/proxyv2:1.21.0
    container_name: ext_proc_demo_envoy
    entrypoint: /usr/local/bin/envoy
    command: [
      "--config-path", "/etc/envoy/envoy.yaml",
      "--log-level", "${ENVOY_LOG_LEVEL:-info}",
      "--service-cluster", "envoy-front",
      "--service-node", "envoy-front",
      "--component-log-level", "filter:debug",
    ]
    environment:
      ENVOY_LOG_LEVEL: debug
    ports:
      - 10000:10000
      - 15000:15000
    networks:
      - ext-proc-demo-network
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml

  ext_proc_demo_service:
    container_name: ext_proc_demo_service
    build:
      context: ./service
    environment:
      CLUSTER_NAME: "service"
      LOG_LEVEL: "debug"
    expose:
      - 8000
      - 8080
    networks:
      - ext-proc-demo-network

  ext_proc_demo_ext_proc:
    container_name: ext_proc_demo_ext_proc
    build:
      context: ./ext-proc
    environment:
      CLUSTER_NAME: "ext_proc"
    expose:
      - 50051
    networks:
      - ext-proc-demo-network

networks:
  ext-proc-demo-network:
    driver: bridge

